import type { Platform } from '@/types';

export const PLATFORMS: Record<string, Platform> = {
  instagram: {
    id: 'instagram', name: 'Instagram', color: '#E1306C',
    bgColor: 'rgba(225,48,108,0.12)', icon: '📸',
    phase: 1, maxChars: 2200,
    mediaTypes: ['image', 'video', 'story', 'reel', 'carousel'],
    maxImages: 10, maxVideoMb: 650,
    supportsScheduling: true, requiresBusinessAccount: true,
    contentTypes: ['post', 'story', 'reel', 'carousel'],
  },
  facebook: {
    id: 'facebook', name: 'Facebook', color: '#1877F2',
    bgColor: 'rgba(24,119,242,0.12)', icon: '👍',
    phase: 1, maxChars: 63206,
    mediaTypes: ['image', 'video', 'carousel', 'story'],
    maxImages: 10, maxVideoMb: 10240,
    supportsScheduling: true,
    contentTypes: ['post', 'story', 'video', 'carousel'],
  },
  twitter: {
    id: 'twitter', name: 'Twitter / X', color: '#1DA1F2',
    bgColor: 'rgba(29,161,242,0.12)', icon: '𝕏',
    phase: 1, maxChars: 280,
    mediaTypes: ['image', 'video'],
    maxImages: 4, maxVideoMb: 512,
    supportsScheduling: true,
    contentTypes: ['post', 'thread'],
  },
  youtube: {
    id: 'youtube', name: 'YouTube', color: '#FF0000',
    bgColor: 'rgba(255,0,0,0.12)', icon: '▶️',
    phase: 1,
    mediaTypes: ['video', 'short'],
    maxVideoMb: 128000,
    supportsScheduling: true,
    contentTypes: ['video', 'short'],
  },
  linkedin: {
    id: 'linkedin', name: 'LinkedIn', color: '#0A66C2',
    bgColor: 'rgba(10,102,194,0.12)', icon: '💼',
    phase: 1, maxChars: 3000,
    mediaTypes: ['image', 'video'],
    maxImages: 9, maxVideoMb: 5120,
    supportsScheduling: true,
    contentTypes: ['post', 'article', 'video'],
  },
  threads: {
    id: 'threads', name: 'Threads', color: '#e5e7eb',
    bgColor: 'rgba(229,231,235,0.1)', icon: '@',
    phase: 1, maxChars: 500,
    mediaTypes: ['image', 'video'],
    maxImages: 10, maxVideoMb: 1024,
    supportsScheduling: false,
    contentTypes: ['post', 'thread'],
  },
  sharechat: {
    id: 'sharechat', name: 'ShareChat', color: '#F58020',
    bgColor: 'rgba(245,128,32,0.12)', icon: '🗣️',
    phase: 2, maxChars: 500,
    mediaTypes: ['image', 'video'],
    maxVideoMb: 500,
    supportsScheduling: true,
    contentTypes: ['post', 'video'],
  },
  moj: {
    id: 'moj', name: 'Moj', color: '#FF2D55',
    bgColor: 'rgba(255,45,85,0.12)', icon: '🎬',
    phase: 2,
    mediaTypes: ['video', 'short'],
    maxVideoMb: 200,
    supportsScheduling: true,
    contentTypes: ['short', 'video'],
  },
  pinterest: {
    id: 'pinterest', name: 'Pinterest', color: '#E60023',
    bgColor: 'rgba(230,0,35,0.12)', icon: '📌',
    phase: 2, maxChars: 500,
    mediaTypes: ['image', 'video'],
    supportsScheduling: true,
    contentTypes: ['pin', 'video'],
  },
  telegram: {
    id: 'telegram', name: 'Telegram', color: '#2AABEE',
    bgColor: 'rgba(42,171,238,0.12)', icon: '✈️',
    phase: 2, maxChars: 4096,
    mediaTypes: ['image', 'video', 'audio'],
    maxVideoMb: 2048,
    supportsScheduling: true,
    contentTypes: ['message'],
  },
  whatsapp: {
    id: 'whatsapp', name: 'WhatsApp Business', color: '#25D366',
    bgColor: 'rgba(37,211,102,0.12)', icon: '💬',
    phase: 2, maxChars: 4096,
    mediaTypes: ['image', 'video', 'audio'],
    maxVideoMb: 64,
    supportsScheduling: true, requiresBusinessAccount: true,
    contentTypes: ['message'],
  },
  snapchat: {
    id: 'snapchat', name: 'Snapchat', color: '#FFFC00',
    bgColor: 'rgba(255,252,0,0.1)', icon: '👻',
    phase: 2,
    mediaTypes: ['image', 'video', 'story'],
    supportsScheduling: false,
    contentTypes: ['story'],
  },
};

export const PHASE_1_PLATFORMS = Object.values(PLATFORMS).filter(p => p.phase === 1);
export const PHASE_2_PLATFORMS = Object.values(PLATFORMS).filter(p => p.phase === 2);
export const ALL_PLATFORMS = Object.values(PLATFORMS);

export const PLAN_LIMITS = {
  free: {
    connectedAccounts: 3,
    postsPerMonth: 30,
    scheduling: false,
    analytics: 'basic' as const,
    draftStorage: 5,
    teamMembers: 1,
    mediaStorageGb: 0.5,
    hashtagSets: 3,
    prioritySupport: false,
    priceMonthly: 0,
    priceAnnually: 0,
  },
  creator: {
    connectedAccounts: 10,
    postsPerMonth: 'unlimited' as const,
    scheduling: true,
    analytics: 'advanced' as const,
    draftStorage: 'unlimited' as const,
    teamMembers: 1,
    mediaStorageGb: 5,
    hashtagSets: 'unlimited' as const,
    prioritySupport: 'email' as const,
    priceMonthly: 499,
    priceAnnually: 4799,
  },
  agency: {
    connectedAccounts: 'unlimited' as const,
    postsPerMonth: 'unlimited' as const,
    scheduling: true,
    analytics: 'full' as const,
    draftStorage: 'unlimited' as const,
    teamMembers: 10,
    mediaStorageGb: 50,
    hashtagSets: 'unlimited' as const,
    prioritySupport: 'phone+email' as const,
    priceMonthly: 1499,
    priceAnnually: 14399,
  },
};

export const OPTIMAL_POST_TIMES: Record<string, { day: string; hour: number; label: string }[]> = {
  instagram: [
    { day: 'Monday',    hour: 9,  label: '9:00 AM' },
    { day: 'Wednesday', hour: 12, label: '12:00 PM' },
    { day: 'Friday',    hour: 18, label: '6:00 PM' },
  ],
  facebook: [
    { day: 'Wednesday', hour: 13, label: '1:00 PM' },
    { day: 'Thursday',  hour: 15, label: '3:00 PM' },
  ],
  twitter: [
    { day: 'Tuesday',  hour: 9,  label: '9:00 AM' },
    { day: 'Wednesday', hour: 12, label: '12:00 PM' },
    { day: 'Friday',   hour: 17, label: '5:00 PM' },
  ],
  linkedin: [
    { day: 'Tuesday',   hour: 10, label: '10:00 AM' },
    { day: 'Wednesday', hour: 8,  label: '8:00 AM' },
    { day: 'Thursday',  hour: 12, label: '12:00 PM' },
  ],
};
